### ISSUE TITLE
Issue loading timezone when parsing ZonedDateTimePattern on web 

### ISSUE THREAD

**Issue by ejlevin1** [Joshua-Ferguson/time_machine#73]
I'm running into an issue where DateTimeZoneProviders.tzdb isn't loading timezones that aren't explicitly loaded at startup.  Is there a way to have timezones dynamically load when trying to be parsed?  I should note that if I do an explicit 
```
await tzdb[<timezone name>];
```
on the timezone being parsed, it works perfectly.  Any thoughts on what I'm doing wrong?  Note, I'm only seeing this on flutter web.

pubspec:
```
dependencies:
  time_machine: ^0.9.17

....

  assets:
    - assets/images/
    - assets/svgs/
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin
    - .env
```

main.dart:
```
    await TimeMachine.initialize({'rootBundle': rootBundle});
    var tzdb = await DateTimeZoneProviders.tzdb;
    final String currentTimeZone =
        await FlutterNativeTimezone.getLocalTimezone();
    log.info('Loading current timezone of [$currentTimeZone]');
    await tzdb[currentTimeZone];
```

https://github.com/Dana-Ferguson/time_machine/assets/555863/5afc16b6-3571-4e87-9ca4-ad4d1fb21085
